In [1]:
import cv2
import numpy as np
from numpy import random

In [2]:
#Load in the original image
demo = cv2.imread("C:/Users/User/realgogo/car2.jpg",cv2.IMREAD_UNCHANGED)
r, c, t = demo.shape

In [3]:
# Display original image
cv2.imshow("Original image", demo)
cv2.waitKey(0)
cv2.destroyAllWindows

<function destroyAllWindows>

In [6]:
# Create random key
key = random.randint(256, size = (r, c, t))
print (key)

[[[198  58  92]
  [217 145 207]
  [ 82  86 255]
  ...
  [219 171 198]
  [151 137  38]
  [137  82  96]]

 [[186 184 231]
  [135 114  98]
  [253 197 148]
  ...
  [ 25 128 108]
  [ 12 103  42]
  [145 179  50]]

 [[ 94 178 103]
  [142  32 111]
  [149 254 201]
  ...
  [180 150  88]
  [122  16  15]
  [ 52 106 200]]

 ...

 [[143 135 115]
  [219  20   2]
  [ 35 147 184]
  ...
  [232 128 102]
  [158 232  51]
  [184   7  67]]

 [[ 62 251 214]
  [ 60  87  39]
  [200 225 210]
  ...
  [ 84  97  68]
  [ 85 101 220]
  [112  82 169]]

 [[113 175 227]
  [  6 232  93]
  [131  31   0]
  ...
  [ 43 165 155]
  [ 66 247   6]
  [ 93  57 162]]]


In [7]:
# Encryption
# Iterate over the image
# Encryption
# Iterate over the image
encrypted_image = np.zeros((r, c, t), np.uint8)
for row in range(r):
    for column in range(c):
        for depth in range(t):
            encrypted_image[row, column, depth] = demo[row, column, depth] ^ key[row, column, depth] 
                 
cv2.imshow("Encrypted image", encrypted_image)
cv2.waitKey(0)
cv2.destroyAllWindows

<function destroyAllWindows>

In [ ]:
# Decryption
# Iterate over the encrypted image
decrypted_image = np.zeros((r, c, t), np.uint8)
for row in range(r):
    for column in range(c):
        for depth in range(t):
            decrypted_image[row, column, depth] = encrypted_image[row, column, depth] ^ key[row, column, depth] 
            
cv2.imshow("Decrypted Image", decrypted_image)
cv2.waitKey(0)
cv2.destroyAllWindows()